/* 2 e 3 FORMAS NORMAIS */
/* 2 FN - CAMPO NÃO CHAVE TEM Q DEPENDER DA TOTALIDADE DA CHAVE */
/* 3 FN - */
CREATE DATABASE CONSULTORIO;
USE CONSULTORIO;
CREATE TABLE PACIENTE(
			 IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
			 NOME VARCHAR(30) NOT NULL,
			 SEXO CHAR(1) NOT NULL,
			 EMAIL VARCHAR(30) NOT NULL UNIQUE,
			 NASCIMENTO DATE NOT NULL
);
CREATE TABLE MEDICO(
			 IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
			 NOME VARCHAR(30) NOT NULL,
			 SEXO CHAR(1) NOT NULL,
			 ESPECIALIDADE VARCHAR(30) NOT NULL,
			 FUNCIONÁRIO ENUM('S','N')
			 );
CREATE TABLE HOSPITAL(
			 IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
			 NOME VARCHAR(30) NOT NULL,
			 BAIRRO VARCHAR(30) NOT NULL,
			 CIDADE VARCHAR(30) NOT NULL,
			 ESTADO CHAR(2)
			 );
CREATE TABLE CONSULTA(
			 IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
			 ID_PACIENTE INT,
			 ID_MEDICO INT,
			 ID_HOSPITAL INT,
			 DATA DATETIME NOT NULL,
			 DIAGNOSTICO VARCHAR(50) NOT NULL
			 );
CREATE TABLE INTERNACAO(
			  IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
			  QUARTO INT NOT NULL,
			  ENTRADA DATETIME NOT NULL,
			  SAIDA DATETIME NOT NULL,
			  OBSERVACOES VARCHAR(50),
			  ID_CONSULTA INT UNIQUE
			 );
ALTER TABLE CONSULTA ADD CONSTRAINT FK_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);			 
			 
ALTER TABLE CONSULTA ADD CONSTRAINT FK_MEDICO
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);			 
			 
ALTER TABLE CONSULTA ADD CONSTRAINT FK_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);			 
			 
ALTER TABLE INTERNACAO ADD CONSTRAINT FK_CONSULTA
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);			 
			 
			 
			 
			 
			 
			 
			 
			 
			 
			 
			 
			 
			 
			 