/* AUTO RELACIONAMENTO */
CREATE DATABASE CURSOS;
CREATE TABLE CURSO(
			IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
			NOME VARCHAR(30),
			HORAS INT,
			VALOR FLOAT(10,2),
			ID_PREREQ INT
);
ALTER TABLE CURSO ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSO (IDCURSO);

INSERT INTO CURSO VALUES(NULL,'BD RELACIONAL',20,400.00,NULL);
INSERT INTO CURSO VALUES(NULL,'BUSINESS INTELLIGENCE',40,800.00,1);
INSERT INTO CURSO VALUES(NULL,'RELATORIOS AVANCADOS',20,600.00,2);
INSERT INTO CURSO VALUES(NULL,'LOGICA PROGRAM',20,400.00,NULL);
INSERT INTO CURSO VALUES(NULL,'RUBY',30,500.00,4);

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ,"SEM REQ") REQUISITO
FROM CURSO;

/* NOME, VALOR, HORAS E O NOME DO PRE REQUISITO DO CURSO */
SELECT CURSO.NOME AS NOME, 
	   CURSO.VALOR AS VALOR,
	   CURSO.HORAS AS CARGA, 
IFNULL (P.NOME, "---") AS PREREQ
FROM CURSO
LEFT JOIN CURSO P
ON P.IDCURSO = CURSO.ID_PREREQ;












