/* Modelagem Básica */

Cliente

NOME VARCHAR(30),
SEXO CHAR(1),
EMAIL VARCHAR(30),
CPF INT(11),
TELEFONE VARCHAR(30),
ENDEREÇO VARCHAR(100)

/* PROCESSO DE MODELAGEM  - RASCUNHO */
/* FASE 01 E FASE 02 - ADM DE DADOS */

/* MODELAGEM CONCEITUAL - PROGRAMA DE MODELAGEM */
/* MODELAGEM LÓGICA */
/* MODELAGEM FÍSICA - SCRIPS DE BANCO */

CREATE DATABASE PROJETO001;

/* CONECTANDO AO BANCO */

USE PROJETO001;

/* CRIANDO A ATABELA DE CLIENTES */

CREATE TABLE CLIENTES(
NOME VARCHAR(30),
SEXO CHAR(1),
EMAIL VARCHAR(30),
CPF INT(11),
TELEFONE VARCHAR(30),
ENDEREÇO VARCHAR(100)   /* NO ENDEREÇO NÃO VAI 'Ç' LEMBRAR

);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES

/* DESCOBRINDO A ESTRUTURA DAS TABELAS NO BANCO */
DESC CLIENTES

/* INSERINDO DADOS NA TABELA */

/* 'OMITINDO O NOME DAS COLUNAS */
INSERT INTO CLIENTE VALUES ('JOÃO', 'M', 'JOAO@GMAIL.COM', 1195874151, '2341514', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 0086548922, '1548788', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES ('FELIX', 'F', NULL, 0669852144, '0303154', 'FELIX BERTA - RUBEM BERTA - PORTO ALEGRE - RS');

/* DESCREVENDO AS COLUNA */
INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE,CPF) VALUES('MARTA','F','BALTAZAR DE OLIVEIRA - RUBEM BERTA - PORTO ALEGRE - RS', '519587416', 69854700);

/* INSERT COMPACTO (APENAS SQL) */
INSERT INTO CLIENTE VALUES ('ALEXANDRE', 'M', 'ALEXANDRE@GMAIL.COM', 2154854, '5874120', 'RUA DAS ORQUIDEAS - SANTA FÉ - PORTO ALEGRE - RS'),
							('LEONARDO', 'M', 'LEONARDO@GMAIL.COM', 1545787, '874510', 'BATISTA FLORES - QUINTANA - PORTO ALEGRE - RS');


/* USANDO O COMANDO SELECT */

SELECT NOW() AS DATA_HORA;

/* FAZENDO PREJEÇÃO DE DADOS DE UMA TABELA */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTES;
SELECT ENDEREÇO, NOME, NOW() AS DATA_HORA FROM CLIENTES;


/* USAR O SELECT * FROM APENAS PARA FINS ACDEMICOS */
/* AUMENTANDO A PERFORMANCE DO BANCO */
 
/* REALIZANDO QUERY DE FILTRO */

/* USANDO O WHERE */
SELECT NOME FROM CLIENTES WHERE SEXO ='M'

/* USANDO O LIKE */
/* O LIKE USA A SEMELHANÇA NO CADASTRO */
SELECT NOME FROM CLIENTES WHERE ENDREÇO LIKE '%RUBEM BERTA%';
/* USANDO O % PARA PESQUISAR INFORMAÇÃO DENTRO DE UM CADASTRO */



/* OUTRO PROJETO */
CREATE TABLE lIVROS001(
TITULO VARCHAR(100),
AUTOR VARCHAR(100),
SEXO CHAR(1),
PAGINAS INT(5),
EDITORA VARCHAR(30),
VALOR FLOAT(10, 2),
UF CHAR(2),
ANO INT (4)
);

/* INSERINDO REGISTROS */
INSERT INTO lIVROS001 VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO lIVROS001 VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO lIVROS001 VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO lIVROS001 VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78,'RJ',2018);
INSERT INTO lIVROS001 VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150,'RJ',2019);
INSERT INTO lIVROS001 VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO lIVROS001 VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO lIVROS001 VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78,'ES',2011);
INSERT INTO lIVROS001 VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130,'RS',2018);
INSERT INTO lIVROS001 VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56,'SP',2017);

/* 1 - TRAZER TODOS OS DADOS */
SELECT TITULO, VALOR, PAGINAS, EDITORA, UF, AUTOR, SEXO FROM lIVROS001;

/* 2 - NOME DO LIVRO E NOME DA EDITORA */
SELECT TITULO, EDITORA FROM lIVROS001;

/* 3 - NOME DO LIVRO E A UF DOS LIVROS ESCRITOS POR AUTORES DO SEXO MASCULINO */
SELECT TITULO, UF FROM lIVROS001 WHERE SEXO = 'M';

/* 4 - NOME DO LIVRO E NUMERO DE PAGINAS DE ESCRITORAS FEMININAS */
SELECT TITULO, PAGINAS FROM lIVROS001 WHERE SEXO = 'F';

/* 5 - VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO */
SELECT VALOR FROM lIVROS001 WHERE UF = 'SP';

/* 6 - TRAZER O NOME DOS AUTORES MASCULINOS QUE TIVERAM LIVROS PUBLICADOS POR EDITORAS DE SP OU RJ */
SELECT AUTOR, SEXO, UF FROM lIVROS001 WHERE SEXO ='M' AND (UF='SP' OR UF= 'RJ');

/* registros nulos */
select nome, email, endereco
from clientes
where email is null;

/* tudo que não for nulo */
select nome, email, endereco
from clientes
where email ins not null;

/* corrigindo registros no banco: função UPDATE */
SELECT nome, email
from cliente;

select * from clientes
where nome ='aaa';
UPDATE clientes
set email='jsndjsn@gmail.com'
where nome = 'aaa';

/* DELETANDO REGISTROS COM FUNÇÃO DELETE */
DELETE FROM CLIENTE
WHERE NOME='AAA';

/* UPDATE */
UPDATE CLIENTE
SET TELEFONE='123456'
WHERE NOME='ALEXANDRE'

